zones = {'USAQUEN':'NOR',
         'CHAPINERO':'CE',
         'SANTA FE':'CE',
         'SAN CRISTOBAL':'S',
         'USME':'S',
         'TUNJUELITO':'S',
         'BOSA':'SO',
         'KENNEDY':'SO',
         'FONTIBON':'CO',
         'ENGATIVA':'CO',
         'SUBA':'NOC',
         'BARRIOS UNIDOS':'NOC',
         'TEUSAQUILLO':'CE',
         'LOS MARTIRES':'CE',
         'ANTONIO NARI—O':'CE',
         'PUENTE ARANDA':'CO',
         'CANDELARIA':'CE',
         'RAFAEL URIBE URIBE':'S',
         'CIUDAD BOLIVAR':'S'}
